/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cbxsqynnbftcywxgxelt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieHNxeW5uYmZ0Y3l3eGd4ZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjIzMDcsImV4cCI6MjA3MzY5ODMwN30.sYxm2sqqayvsPhO7y3Kvb_oDPC-1HOCKV2-1vN2VGCE"